version: 2
refrences:
  ignored-branches: &ignored-branches
     branches:
      ignore:
        - gh-pages

  cache-options: &cache-options
    key: package-cache-{{ checksum "package.json" }}

jobs:
  build:
    working_directory: ~/app/client
    docker:
      - image: circleci/node:12
    steps:
      - checkout
        path: ~/app
      - restore_cache:
          <<: *cache-options
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          <<: *cache-options
          paths:
            - ./node_modules
  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - add_ssh_keys:
          fingerprints:
            - "4b:cd:36:9a:25:09:eb:62:71:a1:57:27:8e:8e:83:79"
      - checkout
      - restore_cache:
          <<: *cache-options
      - run:
          name: deploy-gh-pages
          command: ./bin/deploy


workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            <<: *ignored-branches
      - deploy:
          filters:
            branches:
              only:
                - develop